@startuml
!pragma layout smetana

class Main {
+ static void main(String[] args)
}

class StreamingService{
- String name
- String movieDataPath
- String seriesDataPath
- String userDataPath
- HashMap<String, String> userData
- User currentUser
- TextUI ui
- FileIO io
- MediaManager manager
+ StreamingService(String name)
- void startStreamingService()
- void createUser()
- void addUser(User u)
- void loadUserData()
- void loadWatchlist()
- void homeMenu()


}

class MediaManager {
- TextUI
- FileIO
- ArrayList<Movies> movies
- ArrayList<Series> series
+ MediaManager(ui, io, User currentUser, movieDataPath, seriesDataPath)
+ void searchByTitle(User currentUser)
+ void searchByGenre()
+ void displayMediaInformation(Media media)
+ void playMedia()
- void addToWatchlist(Media media)
+ void medialistInteraction(User currentUser, List<Media> mediaList, String listName)
+ void watchlistInteraction(User currentUser)
+ void prevWatchedlistInteraction(User currentUser)
}

class User {
- String username
- String password
- ArrayList<Media> watchlist
- Collection<Media> prevWatched
+ User(String username, String password)
+ String toString()
+ void addToWatchlist(Media media)
+ String getusername()
+ ArrayList<Media> getWatchlist()
}


abstract class Media{
# String mediaTitle
# double rating
# String genre
# String releaseYear
# String seasonAndEpisodes
+Media(String mediaTitle, String releaseYear, String genre, double rating, String seasonAndEpisodes)
+Media(String mediaTitle, String releaseYear, String genre, double rating)
+String getMediaTitle()
+double getRating()
+String getGenre()
+String getReleaseYear()
+String getSeasonsAndEpisodes()
}

class Movie{
+ Movie(String mediaTitle, String releaseYear, String genre, double rating)
+String toString()
'metode der loader liste over film?

}

class Series{
+Series(String mediaTitle, String releaseYear, String genre, double rating, String seasonAndEpisodes)
+String toString()
'metode der loader liste over serier?
}

class FileIO {
+ HashMap<String, String> readUserData(String path)
+ ArrayList<Movie> readMovieData(String path)
+ ArrayList<Series> readSeriesData(String path)
+ void SaveUserData(String userAsText, String path)
+ void saveMediaList(String username, ArrayList<Media> watchlist, String listType)
+ ArrayList<Media> loadMediaList(String username, String listType)
+ void saveWatchlist(String username, ArrayList<Media> watchlist
+ ArrayList<Media> loadWatchlist(String username)
+ void savePrevWatched(String username, ArrayList<Media> prevWatched)
+ ArrayList<Media> loadPrevWatched(String username)
}

class TextUI {
- Scanner scan
+ void displayMsg(String msg)
+ int displayHomeMenu(String msg)
+ int promptNumeric(String msg)
+ String promptText(String msg)
}

Main *-- StreamingService
StreamingService *-- MediaManager
MediaManager *-- Media
StreamingService *-- User
StreamingService *-- FileIO
StreamingService *-- TextUI
Media <|-- Movie
Media <|-- Series
StreamingService *-- Media
User *-- Media
@enduml