@startuml
!pragma layout smetana

!pragma layout smetana

class Main {
+ static void main(String[] args)
}

class StreamingService{
- String name
- ArrayList<User> users
- TextUI ui
- FileIO io
+ StreamingService(String name)
- void startStreamingService()
- void createUser(String username, String password)
- void loadUserData()
- void homeMenu()
}

class User {
- String username
- String password
}





class FileIO {
- ArrayList<String> readMovieData
- ArrayList<String readSeriesData
+ void saveMovieData(String path)
+ void saveSeriesData(String path)
}

class TextUI {
- Scanner scanner
+ void displayMsg(String msg)
+ int promptNumeric(String msg)
+ String promptText(String msg)
+ boolean promptBoolean (String msg)
}

Main *-- StreamingService
StreamingService *-- User
StreamingService *-- FileIO
StreamingService *-- TextUI
@enduml