@startuml
!pragma layout smetana
'https://plantuml.com/sequence-diagram

object StreamingService

object Media

object MainMenu
object Startmenu
object Movie
object Series
object Genre
object Crime
object War
object Drama
object Family
object Romance
object SciFi
object Seasons
object Episodes
object ReleaseYear
object Rating
object User
User : username
User : password
object Watchlist
object PrevWatched





object FileIO
FileIO : file
object TextUI




StreamingService *-- Media
StreamingService *-- MainMenu
StreamingService *-- Startmenu
StreamingService *-- User
Media <|-- Movie
Media <|-- Series
Movie *-- Genre
Series *-- Genre
Genre <|-- Crime
Genre <|-- War
Genre <|-- Drama
Genre <|-- Family
Genre <|-- Romance
Genre <|-- SciFi
Series *-- Seasons
Seasons *-- Episodes
Media *-- Rating
Media *-- ReleaseYear
User *-- PrevWatched
User *-- WatchList
PrevWatched *-- Media




@enduml