@startuml
!pragma layout smetana
'https://plantuml.com/sequence-diagram

object StreamingService

object Media

object MainMenu
object StartMenu
object Movie
object Series
object Genre
Genre : crime
Genre : war
Genre : drama
Genre : family
Genre : romance
Genre : sciFi
object Seasons
Seasons : episodes
object ReleaseYear
object Rating
object User
User : username
User : password
object WatchList
object PrevWatched





object FileIO
FileIO : file
object TextUI




StreamingService *-- Media
StreamingService *-- MainMenu
StreamingService *-- StartMenu
StreamingService *-- User
Media <|-- Movie
Media <|-- Series
Movie *-- Genre
Series *-- Genre
Series *-- Seasons
Media *-- Rating
Media *-- ReleaseYear
User *-- PrevWatched
User *-- WatchList
WatchList *-- Media
PrevWatched *-- Media




@enduml